### ISSUE TITLE
Rename the groupId

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkus-easy-retrofit#6]
The groupId `io.quarkiverse.quarkus-easy-retrofit` shouldn't have `quarkus-` in it. A better name would be `io.quarkiverse.retrofit`

**Comment by liuziyuan** [comment]
hi @gastaldi ,
Excuse me, do I need to modify the renaming or do you need to modify ith.
Is this file being modified. https://github.com/quarkiverse/quarkiverse-devops/blob/main/terraform-scripts/quarkus-easy-retrofit.tf

**Comment by gastaldi** [comment]
@liuziyuan hi,

> Excuse me, do I need to modify the renaming or do you need to modify ith.

Sorry for not being clear, you need to modify the pom.xml files in your project to use the `io.quarkiverse.retrofit` groupId. No changes in the terraform script are needed.

**Comment by liuziyuan** [comment]
modified
